using Xunit;

namespace FluorineAbpProjectName.EntityFrameworkCore;

[CollectionDefinition(FluorineAbpProjectNameTestConsts.CollectionDefinitionName)]
public class FluorineAbpProjectNameEntityFrameworkCoreCollection : ICollectionFixture<FluorineAbpProjectNameEntityFrameworkCoreFixture>
{

}
