using FluorineAbpProjectName.EntityFrameworkCore;
using Xunit;

namespace FluorineAbpProjectName.EntityFrameworkCore;

public class FluorineAbpProjectNameEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<FluorineAbpProjectNameEntityFrameworkCoreFixture>
{

}
