using FluorineAbpProjectName.EntityFrameworkCore;
using Xunit;

namespace FluorineAbpProjectName;

[CollectionDefinition(FluorineAbpProjectNameTestConsts.CollectionDefinitionName)]
public class FluorineAbpProjectNameWebCollection : FluorineAbpProjectNameEntityFrameworkCoreCollectionFixtureBase
{

}
